### ISSUE TITLE
Use yum module for install software

### ISSUE THREAD

**Issue by ivn86** [bngsudheer/ansible-role-centos_base#12]
https://github.com/bngsudheer/ansible-role-centos_base/blob/25d9cfa2994e7f4275691a68b3895a311f5e9f8d/tasks/main.yml#L7

https://github.com/bngsudheer/ansible-role-centos_base/blob/25d9cfa2994e7f4275691a68b3895a311f5e9f8d/tasks/main.yml#L52

https://github.com/bngsudheer/ansible-role-centos_base/blob/25d9cfa2994e7f4275691a68b3895a311f5e9f8d/tasks/main.yml#L73

... and so on.

**Comment by bngsudheer** [comment]
Could you describe the issue please?

**Comment by ivn86** [comment]
I ran a palybook with sudo (become_method: sudo) and got an error requiring root privileges. But now I think that this is a problem in ansible 2.5. You can leave it as it is or use the module yum for uniformity, in any case you use both methods:

https://github.com/bngsudheer/ansible-role-centos_base/blob/25d9cfa2994e7f4275691a68b3895a311f5e9f8d/tasks/main.yml#L73

https://github.com/bngsudheer/ansible-role-centos_base/blob/25d9cfa2994e7f4275691a68b3895a311f5e9f8d/tasks/main.yml#L3

**Comment by bngsudheer** [comment]
Makes sense. See https://github.com/bngsudheer/ansible-role-centos_base/commit/4d490c8a51acda553419ebe90943e472b7721c0c
